# Generated by Django 5.1.6 on 2025-03-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Jane Doe', max_length=255),
        ),
    ]
