# Generated by Django 5.1.6 on 2025-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
